Reapply "Try out a test failure"
This reverts commit a0466adbc285dc87252162b66afa3ed9f2fe327d. Just to
see how a failure looks in a PR

diff --git a/.github/workflows/test-code.yaml b/.github/workflows/test-code.yaml
--- a/.github/workflows/test-code.yaml
+++ b/.github/workflows/test-code.yaml
@@ -11,6 +11,10 @@ jobs:
     steps:
       - name: test
         run: echo 'testing the code'
+      - name: inject failure
+        run: |
+          echo "tests failed" >&2
+          exit 1
       - name: set output
         id: set-output
         run: echo 'testrun=success' >> "$GITHUB_OUTPUT"
