Try out a test failure

diff --git a/.github/workflows/test-code.yaml b/.github/workflows/test-code.yaml
--- a/.github/workflows/test-code.yaml
+++ b/.github/workflows/test-code.yaml
@@ -8,3 +8,7 @@ jobs:
     steps:
       - name: test
         run: echo 'testing the code'
+      - name: inject failure
+        run: |
+          echo "tests failed" >&2
+          exit 1
